{"uuid": "f5acebba-c33e-4c65-a7c5-cb06fd61f6a6", "children": ["78474ef8-1d9c-4198-b25b-1d04aefee3d6", "cfc26b85-af99-49a0-a227-074e0ca55187"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for firefox; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\n", "trace": "  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"X:\\Automation Testing\\06. CredKart_Pytest_Revision\\testCases\\conftest.py\", line 29, in setup\n    driver = webdriver.Firefox()\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 58, in __init__\n    if finder.get_browser_path():\n       ~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 47, in get_browser_path\n    return self._binary_paths()[\"browser_path\"]\n           ~~~~~~~~~~~~~~~~~~^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 78, in _binary_paths\n    raise NoSuchDriverException(msg) from err\n"}, "start": 1754977166324, "stop": 1754977166574}, {"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for firefox; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\n", "trace": "  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"X:\\Automation Testing\\06. CredKart_Pytest_Revision\\testCases\\conftest.py\", line 29, in setup\n    driver = webdriver.Firefox()\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 58, in __init__\n    if finder.get_browser_path():\n       ~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 47, in get_browser_path\n    return self._binary_paths()[\"browser_path\"]\n           ~~~~~~~~~~~~~~~~~~^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 78, in _binary_paths\n    raise NoSuchDriverException(msg) from err\n"}, "start": 1754977166607, "stop": 1754977166800}], "start": 1754977166607, "stop": 1754977166821}