{"uuid": "bf959069-0c74-4663-8f20-9928917235b8", "children": ["5cd16b08-d6fc-4f4e-8c77-7e7302f4f7e0", "c41c85a3-9c76-4b8e-b06a-1996dcc82532"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for firefox; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\n", "trace": "  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"X:\\Automation Testing\\06. CredKart_Pytest_Revision\\testCases\\conftest.py\", line 29, in setup\n    driver = webdriver.Firefox()\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 58, in __init__\n    if finder.get_browser_path():\n       ~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 47, in get_browser_path\n    return self._binary_paths()[\"browser_path\"]\n           ~~~~~~~~~~~~~~~~~~^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 78, in _binary_paths\n    raise NoSuchDriverException(msg) from err\n"}, "start": 1754977158614, "stop": 1754977159055}, {"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for firefox; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\n", "trace": "  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"X:\\Automation Testing\\06. CredKart_Pytest_Revision\\testCases\\conftest.py\", line 29, in setup\n    driver = webdriver.Firefox()\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 58, in __init__\n    if finder.get_browser_path():\n       ~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 47, in get_browser_path\n    return self._binary_paths()[\"browser_path\"]\n           ~~~~~~~~~~~~~~~~~~^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 78, in _binary_paths\n    raise NoSuchDriverException(msg) from err\n"}, "start": 1754977159124, "stop": 1754977160043}], "start": 1754977159123, "stop": 1754977160076}